version: "3"

services: 
  database:
    image: postgres:15.2
    container_name: guexit_identityProvider_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  webapi:
    container_name: guexit_identityProvider_webapi
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "7192:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ConnectionStrings__Guexit_IdentityProvider_IdentityUsers=Server=database;Port=5432;Database=guexit_identityprovider;User ID=postgres;Password=postgres;
      - ConnectionStrings__Guexit_IdentityProvider_IdentityServerOperationalData=Server=database;Port=5432;Database=guexit_identityprovider;User ID=postgres;Password=postgres;
      - ConnectionStrings__Guexit_ServiceBus=Endpoint=sb://tryguessit-develop-service-bus.servicebus.windows.net/;SharedAccessKeyName=ServicePolicy;SharedAccessKey=CtlNcVptVsHR6q6DXWcxU239vC6u8yjet/rUEstNhdU=
      - Authentication__Google__ClientId=231047044910-456svfn90ou310ib43j268ctoif38nrf.apps.googleusercontent.com
      - Authentication__Google__ClientSecret=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
      - Authentication__Facebook__ClientId=649484549980563
      - Authentication__Facebook__ClientSecret=de219a23a0688faa5ff03b7afd542193
      - IdentityServer__Clients__0__Enabled=true
      - IdentityServer__Clients__0__ClientId=guexit-bff
      - IdentityServer__Clients__0__ClientName=Guexit backend for frontend
      - IdentityServer__Clients__0__ClientSecrets__0__Value=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
      - IdentityServer__Clients__0__AllowedGrantTypes__0=authorization_code
      - IdentityServer__Clients__0__AllowedScopes__0=openid
      - IdentityServer__Clients__0__AllowedScopes__1=profile
      - IdentityServer__Clients__0__AllowedScopes__2=offline_access
      - IdentityServer__Clients__0__AllowedScopes__3=email
      - IdentityServer__Clients__0__RedirectUris__0=https://localhost:44458/signin-oidc
      - IdentityServer__Clients__0__AllowedCorsOrigins__0=https://localhost:44458

      