name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  runAcceptanceTests:
    needs: build
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tryguessit_identityprovider

    steps: 
    - uses: actions/checkout@v3
    - name: Setup .NET SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Generate EF migrations bundle
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        cd /home/runner/work/TryGuessIt.IdentityProvider/TryGuessIt.IdentityProvider/
        dotnet ef migrations bundle -p ./src/TryGuessIt.IdentityProvider.Persistence/TryGuessIt.IdentityProvider.Persistence.csproj -s ./src/TryGuessIt.IdentityProvider.WebApi/TryGuessIt.IdentityProvider.WebApi.csproj -c PersistedGrantDbContext -o 'efbundle_PersistedGrantDbContext.exe'
        dotnet ef migrations bundle -p ./src/TryGuessIt.IdentityProvider.Persistence/TryGuessIt.IdentityProvider.Persistence.csproj -s ./src/TryGuessIt.IdentityProvider.WebApi/TryGuessIt.IdentityProvider.WebApi.csproj -c TryGuessItIdentityDbContext -o 'efbundle_TryGuessItIdentityDbContext.exe'
    - name: Execute database migrations
      run: |
        ./efbundle_TryGuessItIdentityDbContext.exe --connection 'User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=tryguessit_identityprovider;'
      