name: Publish Artifact

concurrency:
  group: PublishArtifact
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml
    
  publish-artifact:
    name: Publish artifact
    needs: build-and-run-tests
    runs-on: ubuntu-latest
    outputs: 
      new-version: ${{ steps.calculate-new-version.outputs.new-version }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.build-and-run-tests.outputs.commit-hash }} 
          fetch-depth: 0
          
      - name: Calculate new version
        id: calculate-new-version
        run: ./.github/scripts/calculate_new_version.sh
        
      - uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/guexit/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/guexit/guexit-identity-provider:${{ steps.calculate-new-version.outputs.new-version }}
          cache-from: type=registry,ref=ghcr.io/guexit/guexit-identity-provider:buildcache
          cache-to: type=registry,ref=ghcr.io/guexit/guexit-identity-provider:buildcache,mode=max
      
      - name: Create release ${{ steps.calculate-new-version.outputs.new-version }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{steps.calculate-new-version.outputs.new-version}} --generate-notes --latest --title v${{steps.calculate-new-version.outputs.new-version}} --target ${{ needs.build-and-run-tests.outputs.commit-hash }}  
        
  deploy-container-app:
      name: Deploy Container App
      needs: publish-artifact
      uses: Guexit/Guexit.Infrastructure/.github/workflows/deploy-container-app-template.yml@main
      with:
        IMAGE_TO_DEPLOY_NAME: guexit-identity-provider:${{ needs.publish-artifact.outputs.new-version }}
        CONTAINER_APP_NAME: guexit-prod-identity-provider
      secrets:
        AZURE_CREDENTIALS_GUEXIT_PRD: ${{ secrets.AZURE_CREDENTIALS_GUEXIT_PRD }}